Repository ngocjohn/vehicle-info-card, pull requests merged in 2024-09, with the labels that each got.

#54 Update fr.json with the last change
  src/languages/fr.json
Labels: translations

#62 Fix: Button not asign to card.
  src/css/styles.css
  src/types.ts
  src/vehicle-info-card.ts
Labels: bug

#63 Feat: Add drag-drop upload images
  src/components/editor/panel-images.ts
  src/utils/editor-image-handler.ts
  src/vehicle-info-card.ts
Labels: enhancement

#69 Feat: Tire card customization & Image slides configuration
  src/components/editor/panel-images.ts
  src/css/styles.css
  src/editor.ts
  src/types/config.ts
  src/vehicle-info-card.ts
Labels: enhancement
